### ISSUE TITLE
What should I put into `FEEDGEN_HOSTNAME` exactly?

### ISSUE THREAD

**Issue by Dinir** [bluesky-social/feed-generator#112]
```
Message from server: could not resolve identity: did:web:...
```
This message keeps coming up whether I set my ip in it, my ip covered my my router's domain in it, and I don't know what exactly I want to put there.

**Comment by andrewpking** [comment]
I also don't know what to put here. I don't have my own domain for webhosting due to financial constraints of being a student. Even a suggestion of a place where I could host this for free in the readme would be nice, or allowing me to serve this from bluesky's servers.
