### ISSUE TITLE
500 Error when trying to update a feed

### ISSUE THREAD

**Issue by alanwsmith** [bluesky-social/feed-generator#30]
I published a few feeds using this modification to `scripts/publishFeedGen.ts`

```
await agent.api.com.atproto.repo.createRecord()
```

I tried to run the script a second time with the same params to add an avatar to a feed and got the following error:

```
alan@dojo feed-generator % yarn publishFeed
yarn run v1.22.17
$ ts-node scripts/publishFeedGen.ts
/Users/alan/Desktop/feed-generator/node_modules/@atproto/xrpc/src/client.ts:125
        throw new XRPCError(resCode, res.body.error, res.body.message)
              ^
XRPCError: Internal Server Error
    at ServiceClient.call (/Users/alan/Desktop/feed-generator/node_modules/@atproto/xrpc/src/client.ts:125:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 500,
  error: 'InternalServerError',
  success: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm not super surprised since the name is `createRecord()`. I tried `updateRecord()` record just to see if it worked, but it didn't. 

Let me know if I can provide more info

**Comment by dholms** [comment]
Yup this was a bug on the PDS. Fixed now & should be working: https://github.com/bluesky-social/atproto/pull/1087

you'll want to use `putRecord` to update an existing feed gen
