### ISSUE TITLE
"user" is a reserved word in Postgres

### ISSUE THREAD

**Issue by aliceisjustplaying** [bluesky-social/feed-generator#32]
Thus if you switch out sqlite3, it will fail to create the table. I set up one called `atproto_user` instead. I think it should default to another name. If it's beyond the scope of the started it should at least be noted in the README because I'm sure plenty of people will run into this.

**Comment by dholms** [comment]
wait do we have a user table here?

**Comment by aliceisjustplaying** [comment]
you do not. only i do. my brain glitched somewhere 🤦‍♀️ apologies

**Comment by dholms** [comment]
haha you're good 😛 

i've made this mistake more times than i care to admit
