### ISSUE TITLE
yarn publishFeed successful, unable to see feed in client

### ISSUE THREAD

**Issue by jabyrd3** [bluesky-social/feed-generator#35]
I've got this running on my server and can verify that it's reachable at the domain i'm providing in the .env file. Posts are being indexed properly and its basically operating almost exactly like the whats-alf feed does.

I'm able to successfully run `yarn publishFeed`, and if i log the return from `agent.api.com.atproto.repo.putRecord` at the end of the script, I can see it was successful? Unfortunately, I think I'm doing something wrong, though; I can't see my feed in the web or ios clients.

Any pointers would be appreciated.

**Comment by jabyrd3** [comment]
Ah, nevermind. I figured out where to find it in the UI, the instructions could be a bit more-thorough.

I'm now seeing an internal server error when the client queries:

```https://bsky.social/xrpc/app.bsky.feed.getFeedGenerator?feed=at%3A%2F%2Fdid%3Aplc%3Ayv6gvhnalg56qtfxh26d5dou%2Fapp.bsky.feed.generator%2Fkabuki-friends
```

**Comment by jabyrd3** [comment]
Its running here, I'll keep plinking at it:

http://bsky.dev.host:2583/xrpc/app.bsky.feed.getFeedSkeleton?feed=at://did:plc:yv6gvhnalg56qtfxh26d5dou/app.bsky.feed.generator/kabuki-friends

**Comment by NetWalker108** [comment]
Hey, dealing with the same issues here. Using Railway.

**Comment by jamesmurdza** [comment]
Having the same issue!

**Comment by dholms** [comment]
Looks like you have the service running on port 3000

Feed Generator needs to serve content over HTTPS on port 443

**Comment by jabyrd3** [comment]
Ah, thank you, I can get a cert tomorrow and get this cleared up.

It's probably worth mentioning in the docs that bsky expects this server to serve tls over 443.

**Comment by dholms** [comment]
Yup I added it in 👍

**Comment by chukaibejih** [comment]
> Ah, thank you, I can get a cert tomorrow and get this cleared up.
> 
> It's probably worth mentioning in the docs that bsky expects this server to serve tls over 443.

Hello, just to clarify, was this the issue you faced? 
![image](https://github.com/bluesky-social/feed-generator/assets/29266211/92804404-4e35-4a54-9761-5c3709cd4197)
