### ISSUE TITLE
Request for more specific examples

### ISSUE THREAD

**Issue by h-fernand** [bluesky-social/feed-generator#56]
Hello! Been trying to wrap my head around this for a few days now. I'm struggling with building feed generators which rely upon user profiles or an authenticated user's personalized feed. Would it be possible to get some examples of say, a "mutuals" feed and a feed based on something to do with the poster's profile? Maybe a feed with only posts from users whose handles start with the letter 'A'?

**Comment by dholms** [comment]
Hey there, you can see some feed examples over here: https://github.com/bluesky-social/atproto/tree/main/packages/bsky/src/feed-gen

Altho that runs on our appview service which has an index of the entire network.

We're going to keep this example simple for now. The dev discord may be a good place to ask around for more examples
