### ISSUE TITLE
invalid did document: did:web:XXX

### ISSUE THREAD

**Issue by Durss** [bluesky-social/feed-generator#63]
Hello !
I think I properly made a custom feed, i published it, but when i try to add it to my feeds Bluesky gives me this error and I'm not sure what's causing this :/
![image](https://github.com/bluesky-social/feed-generator/assets/721001/dfe4aaaa-d972-4735-ba0e-af747cf46d45)

Here is the link to the feed (might delete it at some point as it doesnt work, so i can't promise the link stays valid):
https://bsky.app/profile/did:plc:xitaf2i6zwhmmjuxlum5xofy/feed/diy

My service seems to work properly:
https://bsky-diy.durss.com/xrpc/app.bsky.feed.getFeedSkeleton?feed=at://did:plc:xitaf2i6zwhmmjuxlum5xofy/app.bsky.feed.generator/diy

I saw this issue mentionning that having an IP V6 server may cause this, I disabled it but it changed nothing:
https://github.com/bluesky-social/atproto/issues/1338

I really have no idea what could be wrong.
If someone had a clue it would be greatly appreciated 🙏

**Comment by snorremd** [comment]
I see you use `did:plc:bsky-diy.durss.com` in your https://bsky-diy.durss.com/.well-known/did.json endpoint. This needs to be `did:web:bsky-diy.durss.com` when you use a hostname as your did.

**Comment by Durss** [comment]
Gosh thank you !
I gave up with this, thank you so much for taking time to help me on this !
It now works 🥳
