### ISSUE TITLE
getting only sparse post create events

### ISSUE THREAD

**Issue by yonatanlebo** [bluesky-social/feed-generator#70]
It's been two days that feeds in Hebrew are not receiving new publications.
Even a in the log that shows all the publications that arrive does not have any lines in Hebrew.

The code is the original code.
The only change is the keyword I'm looking for.

**Comment by Durss** [comment]
I believe something has changed since a few days but can't tell what.
I basically only receive very few post creation notifications.
Only one every few seconds where it should most probably be many per second (as it was before).

Because of that my feed misses most, if not all, of what it's supposed to show.

**Comment by b0o** [comment]
Same issue here with not seeing as many post creations as expected. This is not related to Hebrew text. We indexed our most recent post at `2023-11-13T16:03:01.656Z`, about 31 hours ago. We usually see about 500 posts per day that match our algo.

**Comment by Durss** [comment]
Go an answer from the dev discord.
Change `bsky.social` ref to `bsky.network`.
For me it fiexed everything :)

**Comment by b0o** [comment]
@Durss That worked, thank you! Sure would have been nice to have been notified somehow! P.s. where can I find the Discord invite link?

**Comment by Durss** [comment]
@b0o I've edited my answer with a link, you can subscribe to a newsletter to be notified next time something like this happens :)
You can find a list of the atproto related discord server here:
https://atproto.com/community/groups

I went on the [Bluesky API Touchers](https://discord.gg/3srmDsHSZJ) server ;)

**Comment by Durss** [comment]
@yonatanlebo you may want to rename your issue to something like "Getting only sparse post create events" so people have more chances to find the answer :)

**Comment by yonatanlebo** [comment]
> Got an answer from the dev discord. Change every `bsky.social` ref to `bsky.network`. For me it fixed everything :)
> 
> More info about this here : https://atproto.com/blog/bgs-and-did-doc

Thanks to @Durss it works, thank you very much!
