### ISSUE TITLE
Posts simply have stopped showing up 

### ISSUE THREAD

**Issue by ryandhasgit** [bluesky-social/feed-generator#71]
As of yesterday my feed simply stopped showing posts. I have a list of DIDs for those who will appear on the feed, and I am checking in the subsctiption.ts indexing logic if any of the incoming posts match those DIDs. It was working perfectly fine until yesterday, and now when I run it in prod or even locally I can't get a single post to show from someone in that list, including myself. 

I haven't changed any code. Did something change with the firehose? With the post metadata? I'm really at a loss here. If this keeps up I don't really know what to do about the feed.

**Comment by roqvist** [comment]
Change the subscription endpoint in the `.env` file from `wss://bsky.social` to `wss://bsky.network`

More details: https://github.com/bluesky-social/atproto/discussions/1832

**Comment by ryandhasgit** [comment]
@roqvist  wow, that worked. thank you so much!

**Comment by ryandhasgit** [comment]
See solution above
