### ISSUE TITLE
Default feed setup broken?

### ISSUE THREAD

**Issue by cvhammond** [bluesky-social/feed-generator#72]
I setup a custom firehose feed a couple weeks ago but it hasn't updated in a week. When I clone this repo and run `yarn` and `yarn start` no posts get written to console as expected.

Was there a change to the protocol that broke this repo?

**Comment by steveblue** [comment]
I just updated my feeds to the latest and I'm seeing similar results.

**Comment by steveblue** [comment]
I can verify. After seeing my feeds not update for a week, I upgraded my server to the latest from this repo to see if that would help. Feeds are back up after the update, but even if I add a `console.log` to log "every post off the firehose", nothing is logging.

**Comment by tomharting** [comment]
I've found a solution. Changing `wss://bsky.social` to `wss://bsky.network` in `index.ts` does the job for me.

**Comment by steveblue** [comment]
That works @tomharting. Thank you.

**Comment by dholms** [comment]
Yup that should have been fixed by this: https://github.com/bluesky-social/feed-generator/pull/69

Sorry for not fixing that earlier!
